//Timothy Kang
//Professor: Katherine Papademas
//ITM 311-01
//Due Date: 12/8/16
import java.awt.event.ActionEvent; //importing necessary packages
import java.awt.event.ActionListener;
import javax.swing.*;

public class ATMproj extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form ATMproj
     */
    public ATMproj() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	
        transaction = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("IIT Bank and Trust");
        
        //disable parts of the ATM until correct pin is put in
		jButton1.setEnabled(false);
		jButton3.setEnabled(false);
		jButton4.setEnabled(false);
		jButton5.setEnabled(false);
		jButton6.setEnabled(false);
		jRadioButton1.setEnabled(false);
		jRadioButton2.setEnabled(false);
		jComboBox1.setEnabled(false);
		jComboBox2.setEnabled(false);
		jTextField1.setEnabled(false);
		jTextField3.setEnabled(false);
		jTextField4.setEnabled(false);
		jTextArea1.setText("Please enter your PIN number."); //output in textarea1
		
		//GUI code
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPasswordField2.addActionListener(this);
        //add Action Listeners to every button, combobox, textfield, and radio button
        //so if I click on them or enter something, it can be read
        jButton2.setText("Submit");
        jButton2.addActionListener(this);

        jLabel2.setText("PIN NUMBER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton3.setText("Press for current balance");
        jButton3.addActionListener(this);

        jButton1.setText("Press for loan balance");
        jButton1.addActionListener(this);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton7.setText("EXIT");
        jButton7.addActionListener(this);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(245, 245, 245))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"", "Savings Account", "Checking Account", "Loan Payment" }));
        jComboBox1.addActionListener(this);
        //more actionListeners
        jTextField1.addActionListener(this);
        jTextField3.addActionListener(this);

        transaction.add(jRadioButton1);
        jRadioButton1.setText("Deposit");
        jRadioButton1.addActionListener(this);

        transaction.add(jRadioButton2);
        jRadioButton2.setText("Withdraw");
        jRadioButton2.addActionListener(this);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Mortgage", "Car Loan", "Student Loan", "Personal Loan" }));
        jComboBox2.addActionListener(this);

        jTextField4.addActionListener(this);

        jButton4.setText("Submit");
        jButton4.addActionListener(this);

        jButton5.setText("Submit");
        jButton5.addActionListener(this);

        jButton6.setText("Submit");
        jButton6.addActionListener(this);

        jLabel1.setText("Transaction");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(53, 53, 53)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jRadioButton1))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jRadioButton2))
                .addGap(11, 11, 11)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>                                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMproj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMproj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMproj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMproj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATMproj().setVisible(true);
            }
        });
    }

    // Variables declaration                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.ButtonGroup transaction;
    // End of variables declaration                 
    
    //declaring hardcoded variables for ATM values
    int Savings = 3000, Checkings = 3000, Mort = 250000, Student = 55000, Auto = 45000, Person = 4000;
    
	@Override
	
	public void actionPerformed(ActionEvent a) {
		// TODO Auto-generated method stub
		if (a.getSource()==jButton7) //if you click this "exit" button
		{
			System.exit(0); //exits out of program
		}
		if (a.getSource()==jButton2) //if you click "submit" button next to pin
		{
	    	boolean check1 = false; //declaring a few boolean values
	    	boolean check2 = false;
	    	boolean check3 = false;
	    	boolean check4 = false;
	    	boolean check5 = false;
	    	char pin[] = jPasswordField2.getPassword(); //putting pin numbers as char in an array
	    	try{
	        	if (pin[0] >=48  && pin[0]<=56) //since pin is in chars, I am using ascii values
	        	{ //if first value is above or equal to 0 and below or equal to 8
	        		check1 = true; //change boolean to true
	        	} 
	        	if (pin[1] >=49  && pin[1]<=56)
	        	{ //if second value is above or equal to 1 and below or equal to 8
	        		check2 = true; //change boolean to true
	        	}
	        	if (pin[2] >=48  && pin[2]<=56)
	        	{ //if third value is above or equal to 0 and below or equal to 8
	        		check3 = true; //change boolean to true
	        	}
	        	if (pin[3] >=48  && pin[3]<=56)
	        	{ //if fourth value is above or equal to 0 and below or equal to 8
	        		check4 = true; //change boolean to true
	        	}
	        	if (pin.length==4)
	        	{ //making sure that pin is exactly 4 numbers
	        		check5 = true; //change boolean to true
	        	}
	        if (check1 == true && check2 == true && check3 == true && check4 == true && check5 == true)
	        { //if all of these are true, it will display the following
	        jTextArea1.setText("You are logged in.\nName: Tim Kang\nAddress: 3300 So. Federal, Chicago, IL 60616\nCurrent Balance in Savings Account: $" + Savings +"\nCurrent Balance in Checking Account: $" 
	        + Checkings + "\nCurrent Loan Balance--> Mortgage: $" + Mort + "\nCurrent Loan Balance--> Student Loan: $" + Student + "\nCurrent Loan Balance--> Auto Loan: $" + Auto +
	        "\nCurrent Loan Balance--> Personal Loan: $" + Person + "\nWhat kind of transaction would you like to do?");
	        jButton2.setEnabled(false); //disable button next to pin since correct pin is entered
	        jButton1.setEnabled(true); //enable a few buttons
			jButton3.setEnabled(true);
			jComboBox1.setEnabled(true);
	        }
	        else //if one of the checks is false, it will display this
	        {
	        jTextArea1.setText("Invalid Pin Number. Please try again.");
	        }
	    	}
	    	catch(Exception e){ //catching exception
	    	jTextArea1.setText("Invalid Pin Number. Please try again.");
	    	} //using catch to prevent any non number from being put in as pin or less than 4 numbers
		}
		
		if (jComboBox1.getSelectedItem().toString().equals("Savings Account")) //if user chooses savings account in combobox
		{
			jTextField4.setEnabled(false); //disable textfield
			jButton4.setEnabled(false); //enable button
			jTextArea1.setText("Current Balance in Savings Account: $" + Savings); //display this message
			jRadioButton1.setEnabled(true); //enable radio button so you can choose
			jRadioButton2.setEnabled(true);
			jComboBox2.setEnabled(false); //disabled unless Loan is selected
			try //try catch
			{
			if (jRadioButton1.isSelected()) //if Deposit is selected
			{
				jTextField1.setEnabled(true); //enable and disable a few buttons and textfields
				jTextField3.setEnabled(false);
				jButton6.setEnabled(false);
				jButton5.setEnabled(true);
				if (a.getSource()==jButton5) //and "submit" is clicked
				{
					String strDeposit = jTextField1.getText(); //takes text in textfield and convert to string
					int Deposit = Integer.parseInt(strDeposit); //convert string to integer
					Savings = Savings + Deposit; //formula for increasing savings account when money is deposited
					jTextArea1.setText(jTextArea1.getText()+("\nYou have deposited: $" + Deposit + "\nNew Balance after deposit: $" + Savings)); //display new message
				}
			}
			if (jRadioButton2.isSelected()) //if Withdraw is selected
			{
				jTextField3.setEnabled(true); //enable and disable a few buttons and textfields
				jTextField1.setEnabled(false);
				jButton5.setEnabled(false);
				jButton6.setEnabled(true);
				if (a.getSource()==jButton6) //and "submit" is clicked
				{
					String strWithdraw = jTextField3.getText(); //takes text in textfield and converts to string
					int Withdraw = Integer.parseInt(strWithdraw); //convert string to integer
					if (Savings >= Withdraw) //if Savings is greater than or equal to wtihdraw
					{
					Savings = Savings - Withdraw; //subtract withdraw from savings
					jTextArea1.setText(jTextArea1.getText()+("\nYou have withdrawn: $" + Withdraw + "\nNew Balance after withdrawal: $" + Savings)); //display new message
						if (Savings < 500 && Savings >=0) //but if balance is between 0 and 500
						{ //display warning
							jTextArea1.setText(jTextArea1.getText()+("\nWARNING: Your balance is below $500!!!"));
						}
					}
					else //if savings is not greater than or equal to withdraw (causes a negative balance)
					{ //display message and dont subtract anything
						jTextArea1.setText("Your balance cannot go below 0!!!");
					}
				}				
			}
			} catch(Exception e) //catch exception
			{ //prevent letters or any other values that arent integers
		    	jTextArea1.setText("Not a valid value. Please try again.");
		    }
		}
		
		if (jComboBox1.getSelectedItem().toString().equals("Checking Account")) //if user selects Checking Account
		{
			jTextField4.setEnabled(false); //enable and siable a few buttons and textfields and other combobox
			jButton4.setEnabled(false);
			jTextArea1.setText("Current Balance in Checking Account: $" + Checkings); //display message
			jRadioButton1.setEnabled(true);
			jRadioButton2.setEnabled(true);
			jComboBox2.setEnabled(false);
			try //try catch
			{
			if (jRadioButton1.isSelected()) //if "deposit" is selected
			{
				jTextField1.setEnabled(true); //enable and disable fields and buttons
				jTextField3.setEnabled(false);
				jButton6.setEnabled(false);
				jButton5.setEnabled(true);
				if (a.getSource()==jButton5) //if "submit" is clicked
				{
					String strDeposit = jTextField1.getText(); //takes text in textfield and converts to string
					int Deposit = Integer.parseInt(strDeposit); //converts string to integer
					Checkings = Checkings + Deposit; //add deposit to checkings account
					jTextArea1.setText(jTextArea1.getText()+("\nYou have deposited: $" + Deposit + "\nNew Balance after deposit: $" + Checkings)); //display
				}
			}
			if (jRadioButton2.isSelected()) //if "withdraw" is selected
			{
				jTextField3.setEnabled(true); //enable and disable 
				jTextField1.setEnabled(false);
				jButton5.setEnabled(false);
				jButton6.setEnabled(true);
				
				if (a.getSource()==jButton6) //if "submit" is clicked
				{
					String strWithdraw = jTextField3.getText(); //takes text in textfield and converts to string
					int Withdraw = Integer.parseInt(strWithdraw); //converts string to integer
					if (Checkings>=Withdraw) //if checkings is greater than or equal to withdraw
					{
						Checkings = Checkings - Withdraw; //subtract withdraw from checkings
						jTextArea1.setText(jTextArea1.getText()+("\nYou have withdrawn: $" + Withdraw + "\nNew Balance after withdrawal: $" + Checkings)); //display message
						if (Checkings < 500 && Checkings >=0) //if checkings balance is between 0 and 500
						{//display this warning
							jTextArea1.setText(jTextArea1.getText()+("\nWARNING: Your balance is below $500!!!"));
						}
					}
					else //if checkings is less than withdraw
					{ //dont subtract anything and display this message
						jTextArea1.setText("Your balance cannot go below 0!!!");
					}
					
				}
			}
			} catch(Exception e) //catch exception
			{ //prevent any invalid values from being placed
		    	jTextArea1.setText("Not a valid value. Please try again.");
		    }
		}
		
		if (jComboBox1.getSelectedItem().toString().equals("Loan Payment")) //if user selects loan payment
		{
			jRadioButton1.setEnabled(false); //disable a bunch of buttons and textfields
			jRadioButton2.setEnabled(false);
			jTextField1.setEnabled(false);
			jTextField3.setEnabled(false);
			jButton5.setEnabled(false);
			jButton6.setEnabled(false);
			jTextArea1.setText("Please select which loan you would like to make a payment for."); //display
			jComboBox2.setEnabled(true); //enable 2nd combobox
			if (jComboBox2.getSelectedItem().toString().equals("Mortgage")) //if user selects "mortgage"
			{
				jTextField4.setEnabled(true); //enable field and button
				jButton4.setEnabled(true);
				jTextArea1.setText("You have selected \"Mortgage\"\nYour balance is: $" + Mort + "\nMinimum payment for this month is $2000"); //display
				try //try catch
				{
				if (a.getSource()==jButton4) //if user clicks "submit"
				{
					String strMort = jTextField4.getText(); //takes text in textfield and converts to string
					int Minus = Integer.parseInt(strMort); //converts string to integer
					if ((Minus>=2000 && Mort>=Minus) || (Mort<2000 && Mort>=Minus)){ //value has to be greater than or equal to 2000 and mort greater than minus OR mort less than 2000
					Mort = Mort - Minus; //subtract from mort
					jTextArea1.setText(jTextArea1.getText()+("\nYou have made a payment of: $" + Minus + "\nNew balance after payment: $" + Mort)); //display new value
						if (Mort ==0) //is mort is 0
						{ //display
							jTextArea1.setText(jTextArea1.getText()+("\nCongratulations! You have paid off this loan!!!"));
						}
					}
					else if (Minus<2000 && Mort>Minus) //else if minus is less than 2000 and mort is greater than minus
					{
						jTextArea1.setText(jTextArea1.getText()+("\nPayment too little.")); //display
					}
					else if (Mort<Minus) //else if mort is less than minus
					{
						jTextArea1.setText(jTextArea1.getText()+("\nPayment is too big.")); //display
					}
				}
				}catch (Exception e) //catch exceptions
				{ //prevent invalid values from being inputted
					jTextArea1.setText("Not a valid value. Please try again.");
				}
			}
			if (jComboBox2.getSelectedItem().toString().equals("Car Loan")) //if user selects car loan
			{
				jTextField4.setEnabled(true); //enable textfield and button
				jButton4.setEnabled(true);
				jTextArea1.setText("You have selected \"Car Loan\"\nYour balance is: $" + Auto + "\nMinimum payment for this month is $500"); //display
				try //try catch
				{
				if (a.getSource()==jButton4) //if user clicks button
				{
					String strAuto = jTextField4.getText(); //takes text in textfield and converts to string
					int Minus = Integer.parseInt(strAuto); //convert string to integer
					if ((Minus>=500 && Auto>=Minus) || (Auto < 500 && Auto>=Minus)){ //if minus greater than or equal to 500 and auto is greater than minus OR auto is less than 500
					Auto = Auto - Minus; //if it is, subtract from auto
					jTextArea1.setText(jTextArea1.getText()+("\nYou have made a payment of: $" + Minus + "\nNew balance after payment: $" + Auto)); //display
						if (Auto ==0) //if auto is 0
						{ //display
							jTextArea1.setText(jTextArea1.getText()+("\nCongratulations! You have paid off this loan!!!"));
						}
					}
					else if (Minus <500 && Auto> Minus) //else if minus is less than 500 and auto is greater than minus
					{
						jTextArea1.setText(jTextArea1.getText()+("\nPayment too little.")); //display
					}
					else if (Auto<Minus) //else if auto is less than minus
					{
						jTextArea1.setText(jTextArea1.getText()+("\nPayment is too big.")); //display
					}
				}
				}catch (Exception e) //catch exceptions
				{ //prevent invalid values from being inputted
					jTextArea1.setText("Not a valid value. Please try again."); //display
				}
			}
			if (jComboBox2.getSelectedItem().toString().equals("Student Loan")) //if user selects this option
			{
				jTextField4.setEnabled(true); //enable textfield and button
				jButton4.setEnabled(true);
				jTextArea1.setText("You have selected \"Student Loan\"\nYour balance is: $" + Student + "\nMinimum payment for this month is $200"); //display
				try //try catch
				{
				if (a.getSource()==jButton4) //if user clicks on button
				{
					String strStudent = jTextField4.getText(); //takes text from textfield and converts to a string
					int Minus = Integer.parseInt(strStudent); //convert string to integer
					if ((Minus>=200 && Student>=Minus) || (Student<200 && Student>=Minus)){ //if minus is greater than or equal to 200 and studnet is greater than minus OR student is less than 200
					Student = Student - Minus; //subtract from student
					jTextArea1.setText(jTextArea1.getText()+("\nYou have made a payment of: $" + Minus + "\nNew balance after payment: $" + Student)); //display
						if (Student == 0) //if student is 0
						{ 
							jTextArea1.setText(jTextArea1.getText()+("\nCongratulations! You have paid off this loan!!!")); //display
						}
					}
					else if (Minus<200 && Student>Minus) //if minus less than 200 and student is greater than minus
					{ //display
						jTextArea1.setText(jTextArea1.getText()+("\nPayment too little."));
					}
					else if (Student<Minus) //if student is less than minus
					{
						jTextArea1.setText(jTextArea1.getText()+("\nPayment is too big.")); //display
					}
				}
				}catch (Exception e) //catch exceptions
				{ //prevent invalid values from being inputted
					jTextArea1.setText("Not a valid value. Please try again."); //display
				}
			}
			if (jComboBox2.getSelectedItem().toString().equals("Personal Loan")) //if user selects this loan
			{
				jTextField4.setEnabled(true); //enable textfield and button
				jButton4.setEnabled(true);
				jTextArea1.setText("You have selected \"Personal Loan\"\nYour balance is: $" + Person + "\nMinimum payment for this month is $1000"); //display
				try //try catch
				{
				if (a.getSource()==jButton4) //if user clicks on button
				{
					String strPerson = jTextField4.getText(); //takes text from textfield and converts to a string
					int Minus = Integer.parseInt(strPerson); //convert string to integer
					if ((Minus>=1000 && Person>=Minus) || (Person<1000 && Person>=Minus)){ //if minus is greater than or equal to person and person is greater than minus OR person is less than 1000
					Person = Person - Minus; //subtract from person
					jTextArea1.setText(jTextArea1.getText()+("\nYou have made a payment of: $" + Minus + "\nNew balance after payment: $" + Person)); //display
						if (Person ==0) //if person is 0
						{ //display
							jTextArea1.setText(jTextArea1.getText()+("\nCongratulations! You have paid off this loan!!!"));
						}
					}
					else if (Minus<1000 && Person>Minus) //if minus less than 1000 and person is greater than minus
					{
						jTextArea1.setText(jTextArea1.getText()+("\nPayment too little.")); //display
					}
					else if (Person<Minus) //else if person is less than minus
					{
						jTextArea1.setText(jTextArea1.getText()+("\nPayment is too big.")); //display
					}
				}
				}catch (Exception e) //catch exception
				{ //prevent invalid values from being inputted
					jTextArea1.setText("Not a valid value. Please try again."); //display
				}
			}
		}
		
		if (a.getSource()==jButton3) //if user clicks on "Press for current balance"
		{ //display
			jTextArea1.setText("Current Balance in Savings Account: $" + Savings +"\nCurrent Balance in Checking Account: $" + Checkings);
		}
		if (a.getSource()==jButton1) //if user clicks on "Press for loan balance"
		{ //display
			jTextArea1.setText("Current Loan Balance--> Mortgage: $" + Mort + "\nCurrent Loan Balance--> Student Loan: $" + Student + "\nCurrent Loan Balance--> Auto Loan: $" + Auto +
	        "\nCurrent Loan Balance--> Personal Loan: $" + Person);
		}
		}
}